#include "CameraCommands.h"
#include "playback/editor/editing/CameraBindingOps.h"
#include <algorithm>
namespace playback::editor::editing::command {
namespace { model::CameraEntity* camera(model::EditorStateExt&s,const std::string&id){auto it=std::find_if(s.cameras.begin(),s.cameras.end(),[&](const auto&v){return v.id==id;});return it==s.cameras.end()?nullptr:&*it;} void restore(std::optional<model::EditorStateExt>&before,model::EditorStateExt&s){if(before)s=*before;} }
AddFreeCamera::AddFreeCamera(std::string name):mName(std::move(name)){} void AddFreeCamera::execute(model::EditorStateExt&s){mBefore=s;CameraBindingOps::addFreeCamera(s,mName);}void AddFreeCamera::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string AddFreeCamera::label()const{return "Add Free Camera";}
DeleteCamera::DeleteCamera(std::string id):mId(std::move(id)){}void DeleteCamera::execute(model::EditorStateExt&s){mBefore=s;CameraBindingOps::deleteCamera(s,mId);}void DeleteCamera::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string DeleteCamera::label()const{return "Delete Camera";}
CreateBindingCamera::CreateBindingCamera(std::string id,std::string name):mSubActorId(std::move(id)),mName(std::move(name)){}void CreateBindingCamera::execute(model::EditorStateExt&s){mBefore=s;CameraBindingOps::createBindingCamera(s,mSubActorId,mName);}void CreateBindingCamera::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string CreateBindingCamera::label()const{return "Create Binding Camera";}
UnbindCamera::UnbindCamera(std::string id):mId(std::move(id)){}void UnbindCamera::execute(model::EditorStateExt&s){mBefore=s;CameraBindingOps::unbindCamera(s,mId);}void UnbindCamera::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string UnbindCamera::label()const{return "Unbind Camera";}
AddKeyframe::AddKeyframe(std::string id,int tick):mCameraId(std::move(id)),mTick(tick){}void AddKeyframe::execute(model::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);int tick=std::clamp(mTick,0,s.totalTicks);if(!c||c->locked||std::any_of(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.tick==tick;}))return;model::CameraKeyframe key;key.id=mCameraId+".key."+std::to_string(tick);key.tick=tick;if(!c->keys.empty())key=c->keys.back(),key.id=mCameraId+".key."+std::to_string(tick),key.tick=tick;c->keys.push_back(key);std::sort(c->keys.begin(),c->keys.end(),[](const auto&a,const auto&b){return a.tick<b.tick;});}void AddKeyframe::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string AddKeyframe::label()const{return "Add Keyframe";}
MoveKeyframe::MoveKeyframe(std::string c,std::string k,int tick):mCameraId(std::move(c)),mKeyframeId(std::move(k)),mTick(tick){}void MoveKeyframe::execute(model::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked)return;auto it=std::find_if(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id==mKeyframeId;});int targetTick=std::clamp(mTick,0,s.totalTicks);if(it==c->keys.end()||std::any_of(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id!=mKeyframeId&&k.tick==targetTick;}))return;it->tick=targetTick;std::sort(c->keys.begin(),c->keys.end(),[](const auto&a,const auto&b){return a.tick<b.tick;});}void MoveKeyframe::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string MoveKeyframe::label()const{return "Move Keyframe";}
DeleteKeyframe::DeleteKeyframe(std::string c,std::string k):mCameraId(std::move(c)),mKeyframeId(std::move(k)){}void DeleteKeyframe::execute(model::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked)return;c->keys.erase(std::remove_if(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id==mKeyframeId;}),c->keys.end());}void DeleteKeyframe::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string DeleteKeyframe::label()const{return "Delete Keyframe";}
SetKeyframeEasing::SetKeyframeEasing(std::string c,std::string k,model::EasingType e):mCameraId(std::move(c)),mKeyframeId(std::move(k)),mEasing(e){}void SetKeyframeEasing::execute(model::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked)return;auto it=std::find_if(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id==mKeyframeId;});if(it!=c->keys.end())it->easingType=mEasing;}void SetKeyframeEasing::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string SetKeyframeEasing::label()const{return "Set Keyframe Easing";}
SetCameraKind::SetCameraKind(std::string id,model::CameraKind kind):mCameraId(std::move(id)),mKind(kind){}void SetCameraKind::execute(model::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(c&&!c->locked)c->kind=mKind;}void SetCameraKind::undo(model::EditorStateExt&s){restore(mBefore,s);}std::string SetCameraKind::label()const{return "Set Camera Kind";}
}
