#include "CameraCommands.h"
#include "playback/refactor/video-editing/CameraBindingOps.h"
#include <algorithm>
namespace playback::refactor::video_editing {
namespace { editor::CameraEntity* camera(editor::EditorStateExt&s,const std::string&id){auto it=std::find_if(s.cameras.begin(),s.cameras.end(),[&](const auto&v){return v.id==id;});return it==s.cameras.end()?nullptr:&*it;} void restore(std::optional<editor::EditorStateExt>&before,editor::EditorStateExt&s){if(before)s=*before;} }
AddFreeCamera::AddFreeCamera(std::string name):mName(std::move(name)){} void AddFreeCamera::execute(editor::EditorStateExt&s){mBefore=s;CameraBindingOps::addFreeCamera(s,mName);}void AddFreeCamera::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string AddFreeCamera::label()const{return "Add Free Camera";}
DeleteCamera::DeleteCamera(std::string id):mId(std::move(id)){}void DeleteCamera::execute(editor::EditorStateExt&s){mBefore=s;CameraBindingOps::deleteCamera(s,mId);}void DeleteCamera::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string DeleteCamera::label()const{return "Delete Camera";}
CreateBindingCamera::CreateBindingCamera(std::string id,std::string name):mSubActorId(std::move(id)),mName(std::move(name)){}void CreateBindingCamera::execute(editor::EditorStateExt&s){mBefore=s;CameraBindingOps::createBindingCamera(s,mSubActorId,mName);}void CreateBindingCamera::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string CreateBindingCamera::label()const{return "Create Binding Camera";}
UnbindCamera::UnbindCamera(std::string id):mId(std::move(id)){}void UnbindCamera::execute(editor::EditorStateExt&s){mBefore=s;CameraBindingOps::unbindCamera(s,mId);}void UnbindCamera::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string UnbindCamera::label()const{return "Unbind Camera";}
AddKeyframe::AddKeyframe(std::string id,int tick):mCameraId(std::move(id)),mTick(tick){}void AddKeyframe::execute(editor::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked||std::any_of(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.tick==mTick;}))return;editor::CameraKeyframe key;key.id=mCameraId+".key."+std::to_string(mTick);key.tick=std::clamp(mTick,0,s.totalTicks);if(!c->keys.empty())key=c->keys.back(),key.id=mCameraId+".key."+std::to_string(mTick),key.tick=std::clamp(mTick,0,s.totalTicks);c->keys.push_back(key);std::sort(c->keys.begin(),c->keys.end(),[](const auto&a,const auto&b){return a.tick<b.tick;});}void AddKeyframe::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string AddKeyframe::label()const{return "Add Keyframe";}
MoveKeyframe::MoveKeyframe(std::string c,std::string k,int tick):mCameraId(std::move(c)),mKeyframeId(std::move(k)),mTick(tick){}void MoveKeyframe::execute(editor::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked)return;auto it=std::find_if(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id==mKeyframeId;});if(it!=c->keys.end())it->tick=std::clamp(mTick,0,s.totalTicks);std::sort(c->keys.begin(),c->keys.end(),[](const auto&a,const auto&b){return a.tick<b.tick;});}void MoveKeyframe::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string MoveKeyframe::label()const{return "Move Keyframe";}
DeleteKeyframe::DeleteKeyframe(std::string c,std::string k):mCameraId(std::move(c)),mKeyframeId(std::move(k)){}void DeleteKeyframe::execute(editor::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked)return;c->keys.erase(std::remove_if(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id==mKeyframeId;}),c->keys.end());}void DeleteKeyframe::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string DeleteKeyframe::label()const{return "Delete Keyframe";}
SetKeyframeEasing::SetKeyframeEasing(std::string c,std::string k,editor::EasingType e):mCameraId(std::move(c)),mKeyframeId(std::move(k)),mEasing(e){}void SetKeyframeEasing::execute(editor::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(!c||c->locked)return;auto it=std::find_if(c->keys.begin(),c->keys.end(),[&](const auto&k){return k.id==mKeyframeId;});if(it!=c->keys.end())it->easingType=mEasing;}void SetKeyframeEasing::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string SetKeyframeEasing::label()const{return "Set Keyframe Easing";}
SetCameraKind::SetCameraKind(std::string id,editor::CameraKind kind):mCameraId(std::move(id)),mKind(kind){}void SetCameraKind::execute(editor::EditorStateExt&s){mBefore=s;auto*c=camera(s,mCameraId);if(c&&!c->locked)c->kind=mKind;}void SetCameraKind::undo(editor::EditorStateExt&s){restore(mBefore,s);}std::string SetCameraKind::label()const{return "Set Camera Kind";}
}
