#include "SequenceCommands.h"
#include "playback/refactor/editor/models/EditorStateExt.h"
#include "playback/refactor/video-editing/SequenceOps.h"
#include <algorithm>
namespace playback::refactor::video_editing {
SplitSequenceAtPlayhead::SplitSequenceAtPlayhead(int tick) : mTick(tick) {} void SplitSequenceAtPlayhead::execute(editor::EditorStateExt& state) { mBefore = state; SequenceOps::splitAt(state.sequence, mTick); } void SplitSequenceAtPlayhead::undo(editor::EditorStateExt& state) { if (mBefore) state = *mBefore; } std::string SplitSequenceAtPlayhead::label() const { return "Split Sequence"; }
TrimSequenceSegment::TrimSequenceSegment(std::string id, int start, int end) : mId(std::move(id)), mStart(start), mEnd(end) {} void TrimSequenceSegment::execute(editor::EditorStateExt& state) { mBefore = state; SequenceOps::trimSegment(state.sequence, mId, mStart, mEnd); } void TrimSequenceSegment::undo(editor::EditorStateExt& state) { if (mBefore) state = *mBefore; } std::string TrimSequenceSegment::label() const { return "Trim Sequence"; }
DeleteSequenceSegment::DeleteSequenceSegment(std::string id) : mId(std::move(id)) {} void DeleteSequenceSegment::execute(editor::EditorStateExt& state) { mBefore = state; auto it = std::find_if(state.sequence.begin(), state.sequence.end(), [&](const auto& segment) { return segment.id == mId; }); if (it != state.sequence.end()) SequenceOps::deleteSegment(state.sequence, std::distance(state.sequence.begin(), it), state.totalTicks); } void DeleteSequenceSegment::undo(editor::EditorStateExt& state) { if (mBefore) state = *mBefore; } std::string DeleteSequenceSegment::label() const { return "Delete Sequence Segment"; }
BindSequenceToCamera::BindSequenceToCamera(std::string id, std::string cameraId) : mId(std::move(id)), mCameraId(std::move(cameraId)) {} void BindSequenceToCamera::execute(editor::EditorStateExt& state) { mBefore = state; auto it = std::find_if(state.sequence.begin(), state.sequence.end(), [&](const auto& segment) { return segment.id == mId; }); if (it != state.sequence.end() && !it->locked) SequenceOps::bindCamera(*it, mCameraId); } void BindSequenceToCamera::undo(editor::EditorStateExt& state) { if (mBefore) state = *mBefore; } std::string BindSequenceToCamera::label() const { return "Bind Sequence Camera"; }
}
